# See: https://github.com/fluent/helm-charts/blob/main/charts/fluent-bit/values.yaml
# For more configuration parameters

config:
  filters: |
    [FILTER]
        Name kubernetes
        Match kube.*
        Merge_Log On
        Keep_Log Off
        K8S-Logging.Parser On
        K8S-Logging.Exclude On

    [FILTER]
        Name parser
        Match kube.*
        Key_name log
        Reserve_data True
        Parser json

    [FILTER]
        Name modify
        Match kube.*
        Rename log @m
  outputs: |
    [OUTPUT]
        Name http
        Match kube.*
        Host seq-dev.default.svc.cluster.local
        Port 5341
        URI /api/events/raw?clef
        Format json_lines
        Json_date_key @t
        Json_date_format iso8601
        Log_response_payload False
