apiVersion: v1
kind: Pod
metadata:
  name: counter
  labels: {
    "log.category": "app"
  }
spec:
  containers:
  - name: count
    image: ubuntu:20.04
    args: [/bin/sh, -c, 'i=0; while true; do echo "{\"@l\":\"info\",\"@mt\":\"{i}: {date}\",\"i\":$i,\"date\":\"$(date)\"}"; i=$((i+1)); sleep 1; done']
